### ISSUE TITLE
Why no longer maintained? 

### ISSUE THREAD

**Issue by trusktr** [IndigoUnited/js-dejavu#61]
Native `class`es still don't have protected or private members, etc, so Dejavu  can still be very useful.

This lib still has more downloads per week than many other class inheritance libs on NPM.

This lib has one of the most awesome implementations of protected and private, which is completely useful for some people that value this type of feature (in fact this inheritance lib has more downloads on NPM than many other inheritance libs).

The big red deprecation warning on NPM is overkill:

![screenshot 2018-03-22 at 10 49 37 am](https://user-images.githubusercontent.com/297678/37788459-bd417b64-2dbe-11e8-9296-f97c39737bc3.png)

By the way, I stumbled on this because I was searching around after implementing https://github.com/trusktr/lowclass which also has protected and private members. I had no idea something like this one existed! Pretty cool!

**Comment by satazor** [comment]
Hello @trusktr 

Thanks for your feedback. You see, when I developed this library, I was a OOP evangelist because that's what they teach you in university. But since then, I've changed opinions and I love how easy, composable and future-proof functional programming is. Even if I need to use OOP, like classes, I no longer feel that forcing other languages OOP features into a language that was not designed to work that way is really that important.

Because I'm no longer using nor maintaining this project, I decided to deprecate it. Though, I can make you a maintainer of the package if you want to keep the project alive. I don't know if you want to do this, since you developed `lowclass`.

Regarding the deprecated message, I messed up something because the message is simply "No". Perhaps I forgot to put it in quotes when I ran `$ npm deprecate <reason>`.
